## Exceptions

Java 使用异常处理错误和异常事件。

**定义**：异常是一种事件，是扰乱程序正常执行流程的事件。

当方法执行中发生错误时，会创建异常对象（包含错误信息，类型和状态等），并传递给运行时系统。这个创建和传递过程叫做抛出异常。

当运行时系统收到异常时，会尝试寻找相应的解决方法。搜索路径是一个有序方法链。这个方法链叫做调用栈。

![调用栈](./imgs/exceptions-callstack.gif)

如图所示，main函数经过一系列调用，调用了发生异常的方法。运行时系统从异常发生方法反向搜索调用栈。如果找到相应的异常处理函数，则把异常交由其处理。

异常处理函数——抓住异常。如果未找到对应的处理函数，则运行时系统会直接终止。

**优点：**

1. 从常规代码中分理处异常处理程序
2. 自动向上传播错误（利用调用栈），只用关心该异常的方法会处理该异常
3. 错误类型的分组和区分。利用异常的子类和父类

### Catch 和 指定要求

对于可能产生异常的代码，有两种处理方式：

* try{....异常代码...}catch{....}
* 使用 Throws指明调用该代码的函数可能抛出异常。

#### 三种异常种类

1. 检验异常。程序可预测的，并能从中恢复的异常。如：`java.io.FileNotFoundException`. 除了`Error`, `RuntimeException`, 和他们的子类，所有异常都是检验异常。
2. 错误。程序外部的异常。如：`java.io.IOError`
3. 运行时异常。程序不可预测的内部错误。像是逻辑错误或者不正确的API使用。如：`NullPointerException`

### Catch 和 异常处理

```java
try{
    .......
    //可能产生异常的代码
}catch(ExceptionType1 e){
    .......
    //实际的异常处理代码，ExceptionType 表示异常类型
    //如果抛出的异常能够赋值给此处的 ExceptionType。即为相配
    //相同类型或者子类
}catch(ExceptionType2 e){
    .......
    //实际的异常处理代码，ExceptionType 表示异常类型
    //如果抛出的异常能够赋值给此处的 ExceptionType。即为相配
    //相同类型或者子类
    //catch 可有多个
}finally{
    //在try Block推出时执行，即使有异常发生。
    //可以避免clean code被绕过，保护资源泄露
    .......
}
```

java SE7 之后，一个Catch Block可以处理多种类型：

```java
catch (IOException|SQLException ex) {
    logger.log(ex);
    //此时ex类型为final
    throw ex;
}
```

**注意：**若在执行try 和catch 时，JVM 推出或者线程被中断或杀死，finally可能不会执行。

#### try-with-resources statement

确保在语句结束时，资源被关闭。所有实现了 java.lang.AutoCloseable 或者java.io.Closeable 接口的，可以作为resource。

```java
static String readFirstLineFromFile(String path) throws IOException {
    try (BufferedReader br =
                   new BufferedReader(new FileReader(path))) {
        return br.readLine();
    }
}
```

上段代码中，BufferedReader实现了 java.lang.AutoCloseable（SE7之后），所以在使用上述语法时，无论 try 语句是否正常完成，都将自动关闭。

**注意：**在函数声明抛出异常时，

* 当 try block 和finally都抛出异常时，try block异常将被忽略
* 当 try block 和try-with-resources statement都抛出异常时，ry-with-resources statement异常将被忽略（上例中来自try block）。可通过对抛出的异常使用`Throwable.getSuppressed`获取。（Exception是Throwable的子类）

### 声明函数抛出的异常

```java
public void writeList() throws IOException, IndexOutOfBoundsException 
//IndexOutOfBoundsException 是unchecked异常，所以不是强制的
```

### 如何抛出异常

所有的异常都是Throwable 的后代，而且所有的异常都可以被继承细分。当然也可以创建自己的异常类（或者链式异常）

```java
throw someThrowableObject;
```

#### 抛出类和子类

![Throwable层次](./imgs/exceptions-throwable.gif)

##### Error

JVM 错误，简单程序不能catch 或者throw Error。

##### Exception

可以继承创建自己的异常类

#### 链式异常

碰到异常时，应用通常抛出异常来回应。在 Throwable 中有以下方法：

```java
Throwable getCause()//返回造成当前异常的异常
Throwable initCause(Throwable)//参数Throwable为造成当前异常的异常
Throwable(String, Throwable)//参数Throwable为造成当前异常的异常
Throwable(Throwable)//参数Throwable为造成当前异常的异常
```

```java
try {

} catch (IOException e) {
    
    //当抓到IOException 时，返回一个SampleException
    throw new SampleException("Other IOException", e);
}
```

##### 获取栈路径

栈路径提供当前线程的执行历史。

```java
 StackTraceElement elements[] = cause.getStackTrace();//cause为异常
cause.printStackTrace();
```

### Unchecked Exceptions — The Controversy

当然可以只写抛出 RuntimeException 的代码，或者所有的异常都继承它。这样就可以不用异常处理。（try-catch-finally 不抓取这类异常）。但这并不提倡。 RuntimeException会增加代码工作量（可能随时发生）。